# Generated by Django 3.1.7 on 2021-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_accountant_attendant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='StoreKeeper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ATTENDANT', 'Attendant'), ('CASHIER', 'Cashier'), ('STORE_KEEPER', 'Store_keeper'), ('ACCOUNTANT', 'Accountant'), ('SUPERVISOR', 'Supervisor')], default='SUPERVISOR', max_length=100, verbose_name='Role'),
        ),
    ]
