version: "3.4"
services:
  app:
    build:
      context: .
      target: dev
    working_dir: /opt/project/src
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - PYTHONPATH=/opt/project
    volumes:
      - .:/opt/project
  postgres:
    image: postgres:9.6
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD

volumes:
  pg-data:
    driver: local